ALTER PROCEDURE "SP_ORDENES_COMPRA_CAB_INSERT"
(
  "NUMERO" VARCHAR(30),
  "PROVEEDOR_ID" INTEGER,
  "OBSERVACIONES" VARCHAR(250),
  "NUMERO_REFERENCIA" VARCHAR(30),
  "FECHA_EMISION" DATE,
  "CONDICION_COMPRA_ID" INTEGER,
  "ESTADO_COD" VARCHAR(50),
  "CANTIDAD_PEDIDA" INTEGER,
  "IMPORTE_TOTAL" NUMERIC(9,0),
  "NUMERO_VERSION" INTEGER,
  "LOGIN_CREACION" VARCHAR(50),
  "LOGIN_ULT_MODIF" VARCHAR(50),
  "MONEDA_OPERACION_ID" INTEGER,
  "COTIZACION" NUMERIC(9, 0)
)
RETURNS
(
  "PO_I_ORDEN_COMPRA_ID" INTEGER
)
AS
BEGIN

    /********************************************/
    /* Tomo el próximo valor del generador.     */
    /********************************************/
    po_i_orden_compra_id = GEN_ID ( SP_ORDENES_COMPRA_CAB_G , 1 );

    /********************************************/
    /* Inserto el nuevo registro en la tabla.   */
    /********************************************/
    INSERT INTO "ORDENES_COMPRA_CAB"
    (
		"ORDEN_COMPRA_CAB_ID",
		"ORDEN_COMPRA_NRO",
		"PROVEEDOR_ID",
		"OBSERVACIONES",
		"NUMERO_REFERENCIA",
		"FECHA_EMISION",
		"CONDICION_COMPRA_ID",
		"ESTADO_COD",
		"CANTIDAD_PEDIDA_TOTAL",
		"CANTIDAD_RECIBIDA_TOTAL",
		"IMPORTE_TOTAL",
		"NUMERO_VERSION",
		"LOGIN_CREACION",
		"FECHA_CREACION",
		"LOGIN_ULT_MODIF",
		"FECHA_ULT_MODIF",
		"MONEDA_OPERACION_ID",
		"MONEDA_NACIONAL_ID",
		"COTIZACION"
    )
    VALUES
    (
		:"PO_I_ORDEN_COMPRA_ID",
		:"NUMERO",
		:"PROVEEDOR_ID",
		:"OBSERVACIONES",
		:"NUMERO_REFERENCIA",
		:"FECHA_EMISION",
		:"CONDICION_COMPRA_ID",
		:"ESTADO_COD",
		:"CANTIDAD_PEDIDA",
		0,
		:"IMPORTE_TOTAL",
		:"NUMERO_VERSION",
		:"LOGIN_CREACION",
		CURRENT_TIMESTAMP,
		:"LOGIN_CREACION",
		CURRENT_TIMESTAMP,
		:"MONEDA_OPERACION_ID",
		(SELECT moneda_id FROM monedas WHERE moneda_cod = 'PES'),
		:"COTIZACION"
    );

    SUSPEND;

END

