COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */

CREATE PROCEDURE "SP_ORDENES_COMPRA_LINEAS_UPDATE" 
(
  "ORDEN_COMPRA_LINEA_ID" INTEGER,
  "ARTICULO_X_PROVEEDOR_ID" INTEGER,
  "CANTIDAD_PEDIDA" NUMERIC(12, 3),
  "PRECIO_UNITARIO" NUMERIC(12, 3),
  "FECHA_RECEPCION" DATE,
  "CANTIDAD_RECIBIDA" NUMERIC(12, 3),
  "PORC_DESCUENTO" NUMERIC(12, 3),
  "ORDEN_COMPRA_CAB_ID" INTEGER,
  "UNIDAD_MEDIDA_COD" VARCHAR(50),
  "LOGIN_ULT_MODIF" VARCHAR(50)
)
RETURNS
(
  "PO_I_ORDEN_COMPRA_LINEA_ID" INTEGER
)
AS
BEGIN EXIT; END ^


ALTER PROCEDURE "SP_ORDENES_COMPRA_LINEAS_UPDATE" 
(
  "ORDEN_COMPRA_LINEA_ID" INTEGER,
  "ARTICULO_X_PROVEEDOR_ID" INTEGER,
  "CANTIDAD_PEDIDA" NUMERIC(12, 3),
  "PRECIO_UNITARIO" NUMERIC(12, 3),
  "FECHA_RECEPCION" DATE,
  "CANTIDAD_RECIBIDA" NUMERIC(12, 3),
  "PORC_DESCUENTO" NUMERIC(12, 3),
  "ORDEN_COMPRA_CAB_ID" INTEGER,
  "UNIDAD_MEDIDA_COD" VARCHAR(50),
  "LOGIN_ULT_MODIF" VARCHAR(50)
)
RETURNS
(
  "PO_I_ORDEN_COMPRA_LINEA_ID" INTEGER
)
AS
BEGIN

	UPDATE ORDENES_COMPRA_CAB
	SET "CANTIDAD_PEDIDA_TOTAL" = "CANTIDAD_PEDIDA_TOTAL" + :"CANTIDAD_PEDIDA",
		"CANTIDAD_RECIBIDA_TOTAL" = "CANTIDAD_RECIBIDA_TOTAL" + :"CANTIDAD_RECIBIDA",
		"IMPORTE_TOTAL" = "IMPORTE_TOTAL" + :"PRECIO_UNITARIO" * :"CANTIDAD_PEDIDA",
		"LOGIN_ULT_MODIF" = :"LOGIN_ULT_MODIF",
		"FECHA_ULT_MODIF" = CURRENT_TIMESTAMP;

    IF ( ORDEN_COMPRA_LINEA_ID > 0 ) THEN BEGIN
		UPDATE ORDENES_COMPRA_LINEAS
		SET "CANTIDAD_PEDIDA" = :"CANTIDAD_PEDIDA",
			"PRECIO_UNITARIO" = :"PRECIO_UNITARIO",
			"FECHA_RECEPCION" = :"FECHA_RECEPCION",
			"CANTIDAD_RECIBIDA" = :"CANTIDAD_RECIBIDA",
			"PORC_DESCUENTO" = :"PORC_DESCUENTO",
			"ORDEN_COMPRA_CAB_ID" = :"ORDEN_COMPRA_CAB_ID",
			"UNIDAD_MEDIDA_COD" = :"UNIDAD_MEDIDA_COD"
		WHERE "ORDEN_COMPRA_LINEA_ID" = :ORDEN_COMPRA_LINEA_ID;
	END
    ELSE BEGIN
		EXECUTE PROCEDURE SP_ORDENES_COMPRA_LINEAS_INSERT(
			:"ARTICULO_X_PROVEEDOR_ID",
			:"CANTIDAD_PEDIDA",
			:"PRECIO_UNITARIO",
			:"FECHA_RECEPCION",
			:"CANTIDAD_RECIBIDA",
			:"PORC_DESCUENTO",
			:"ORDEN_COMPRA_CAB_ID",
			:"UNIDAD_MEDIDA_COD"
		)RETURNING_VALUES :PO_I_ORDEN_COMPRA_LINEA_ID;

	END

    SUSPEND;

END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
