ALTER PROCEDURE "SP_ORDENES_COMPRA_LINEAS_UPDATE"
(
  "ORDEN_COMPRA_LINEA_ID" INTEGER,
  "ARTICULO_X_PROVEEDOR_ID" INTEGER,
  "CANTIDAD_PEDIDA" NUMERIC(12, 3),
  "PRECIO_UNITARIO" NUMERIC(12, 3),
  "FECHA_RECEPCION" DATE,
  "CANTIDAD_RECIBIDA" NUMERIC(12, 3),
  "PORC_DESCUENTO" NUMERIC(12, 3),
  "ORDEN_COMPRA_CAB_ID" INTEGER,
  "UNIDAD_MEDIDA_COD" VARCHAR(50)
)
AS
BEGIN

     UPDATE ORDENES_COMPRA_LINEAS
     SET "CANTIDAD_PEDIDA" = :"CANTIDAD_PEDIDA",
         "PRECIO_UNITARIO" = :"PRECIO_UNITARIO",
	 "FECHA_RECEPCION" = :"FECHA_RECEPCION",
	 "CANTIDAD_RECIBIDA" = :"CANTIDAD_RECIBIDA",
	 "PORC_DESCUENTO" = :"PORC_DESCUENTO",
	 "ORDEN_COMPRA_CAB_ID" = :"ORDEN_COMPRA_CAB_ID",
	 "UNIDAD_MEDIDA_COD" = :"UNIDAD_MEDIDA_COD"
    WHERE "ORDEN_COMPRA_LINEA_ID" = :ORDEN_COMPRA_LINEA_ID;

    SUSPEND;

END