
/* View: VW_ARTICULOS, Owner: SYSADMIN */

CREATE VIEW "VW_ARTICULOS" (
  "ARTICULO_X_PROVEEDOR_ID", 
  "PROVEEDOR_ID", 
  "PROVEEDOR_COD", 
  "PROVEEDOR_NOMBRE", 
  "ARTICULO_COD", 
  "ARTICULO_NOMBRE", 
  "ARTICULO_DESC", 
  "FLAG_ACTIVO", 
  "MONEDA_ID", 
  "MONEDA_COD", 
  "MONEDA_NOMBRE", 
  "PRECIO_EN_MONEDA", 
  "PENDIENTE_RECEPCION", 
  "NUMERO_VERSION", 
  "RUBRO_ID", 
  "RUBRO_COD", 
  "RUBRO_NOMBRE", 
  "ARTICULO_DESC2", 
  "CODIGO_BARRAS", 
  "COSTO_RMB", 
  "COTIZACION", 
  "UNIDADES_X_BULTO", 
  "COSTO_INNER", 
  "COSTO_CBM", 
  "PESO_NETO", 
  "PESO_BRUTO", 
  "OBSERVACIONES_1", 
  "OBSERVACIONES_2", 
  "OBSERVACIONES_3", 
  "FECHA_CARGA", 
  "URL_IMAGEN"
) AS
 select A."ARTICULO_X_PROVEEDOR_ID", P."PROVEEDOR_ID", P."PROVEEDOR_COD", P."PROVEEDOR_NOMBRE", A."ARTICULO_COD", A."ARTICULO_NOMBRE", A."ARTICULO_DESC", A."FLAG_ACTIVO", M."MONEDA_ID", M."MONEDA_COD", M."MONEDA_NOMBRE", A."PRECIO_EN_MONEDA", A."PENDIENTE_RECEPCION", A."NUMERO_VERSION", R."RUBRO_ID", R."RUBRO_COD", R."RUBRO_NOMBRE", A."ARTICULO_DESC2", A."CODIGO_BARRAS", A."COSTO_RMB", A."COTIZACION", A."UNIDADES_X_BULTO", A."COSTO_INNER", A."COSTO_CBM", A."PESO_NETO", A."PESO_BRUTO", A."OBSERVACIONES_1", A."OBSERVACIONES_2", A."OBSERVACIONES_3", A."FECHA_CARGA", "URL_IMAGEN"
from articulos_x_proveedores a
INNER JOIN proveedores p
        ON a.proveedor_id = p.proveedor_id
INNER JOIN monedas m
        ON a.moneda_id = m.moneda_id
LEFT  JOIN rubros r
        ON a.rubro_id = r.rubro_id
;
