CREATE PROCEDURE "SP_ORDENES_COMPRA_CAB_DELETE"
(
  "ORDEN_COMPRA_CAB_ID" INTEGER
)
AS
BEGIN

    DELETE FROM  "ORDENES_COMPRA_CAB" F
    WHERE   F."ORDEN_COMPRA_CAB_ID" = :"ORDEN_COMPRA_CAB_ID"
    ;

    EXIT;

END