ALTER PROCEDURE "SP_ORDENES_COMPRA_CAB_UPDATE"
(
  "ORDEN_COMPRA_ID" INTEGER,
  "NUMERO" VARCHAR(30),
  "PROVEEDOR_ID" INTEGER,
  "OBSERVACIONES" VARCHAR(250),
  "NUMERO_REFERENCIA" VARCHAR(30),
  "FECHA_EMISION" DATE,
  "CONDICION_COMPRA_ID" INTEGER,
  "ESTADO_COD" VARCHAR(50),
  "CANTIDAD_PEDIDA" INTEGER,
  "IMPORTE_TOTAL" NUMERIC(9, 0),
  "NUMERO_VERSION" INTEGER,
  "LOGIN_ULT_MODIF" VARCHAR(50),
  "MONEDA_OPERACION_ID" INTEGER,
  "COTIZACION" NUMERIC(9, 0)
)
AS
BEGIN

    /********************************************/
    /* Inserto el nuevo registro en la tabla.   */
    /********************************************/
    UPDATE "ORDENES_COMPRA_CAB"
    SET 
		"ORDEN_COMPRA_NRO" = :"NUMERO",
		"PROVEEDOR_ID" = :"PROVEEDOR_ID",
		"OBSERVACIONES" = :"OBSERVACIONES",
		"NUMERO_REFERENCIA" = :"NUMERO_REFERENCIA",
		"FECHA_EMISION" = :"FECHA_EMISION",
		"CONDICION_COMPRA_ID" = :"CONDICION_COMPRA_ID",
		"ESTADO_COD" = :"ESTADO_COD",
		"CANTIDAD_PEDIDA_TOTAL" = :"CANTIDAD_PEDIDA",
		"CANTIDAD_RECIBIDA_TOTAL" = 0,
		"IMPORTE_TOTAL" = :"IMPORTE_TOTAL",
		"LOGIN_ULT_MODIF" = :"LOGIN_ULT_MODIF",
		"FECHA_ULT_MODIF" = CURRENT_TIMESTAMP,
		"MONEDA_OPERACION_ID" = :"MONEDA_OPERACION_ID",
		"MONEDA_NACIONAL_ID" = (SELECT moneda_id FROM monedas WHERE moneda_cod = 'PES'),
		"COTIZACION" = :"COTIZACION"
    WHERE "ORDEN_COMPRA_CAB_ID" = :"ORDEN_COMPRA_ID";

    SUSPEND;

END

