CREATE PROCEDURE "SP_ORDENES_COMPRA_LINEAS_DELETE"
(
  "ORDEN_COMPRA_LINEA_ID" INTEGER
)
AS
BEGIN

    DELETE FROM  "ORDENES_COMPRA_LINEAS" F
    WHERE   F."ORDEN_COMPRA_LINEA_ID" = :"ORDEN_COMPRA_LINEA_ID"
    ;

    EXIT;

END